import React from 'react';

class Politica extends React.Component {
    render() {
        return (
            <div>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam fringilla iaculis commodo. Maecenas at turpis vitae ipsum mattis molestie. Aliquam erat volutpat. Nullam molestie purus at tempus semper. Vestibulum tincidunt pharetra risus nec ultricies. Maecenas tempor enim at odio tincidunt laoreet. Pellentesque ut vulputate sapien.

Aenean augue velit, tempus malesuada nibh a, faucibus mattis elit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In ultricies vestibulum nibh, vitae lobortis lectus tempor sed. Praesent rutrum volutpat lacus ac lacinia. Morbi tellus leo, aliquam sed vehicula vitae, dapibus non lacus. Curabitur nisl lorem, semper at urna et, efficitur posuere augue. Aliquam erat volutpat. Donec aliquet ut metus in fringilla. Aenean sit amet turpis eget lectus porttitor blandit a eget arcu. Suspendisse ipsum odio, imperdiet sit amet vulputate faucibus, dictum a velit. Fusce vitae lacus a quam imperdiet porttitor id ultricies elit. Cras sit amet mauris et erat suscipit volutpat quis ut urna. Nullam purus enim, mattis sit amet malesuada at, rhoncus a justo.

Aliquam quis magna ut diam maximus feugiat quis vitae felis. Nulla convallis, sem quis tincidunt fermentum, nunc massa efficitur turpis, eu pharetra lorem velit eu est. Nunc volutpat ante in eros aliquet ullamcorper. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed ut commodo ligula. Cras quis ex quam. Vivamus cursus massa id metus ultricies commodo vel ac nisl. Mauris ut ex quis elit sollicitudin hendrerit eget sed dui. Nunc in bibendum elit, vitae imperdiet felis. Maecenas ut hendrerit lorem. In eget lorem enim. Sed gravida odio sem, non placerat nunc congue id. Sed accumsan erat luctus diam suscipit, id placerat ex fringilla. Aliquam viverra tincidunt scelerisque. Sed facilisis elit at purus mattis accumsan.

Maecenas in nulla a nisl condimentum tincidunt ac vehicula nibh. Sed est massa, accumsan egestas quam sed, eleifend egestas mi. Ut vel iaculis mi. Mauris a ipsum porttitor, tincidunt felis non, molestie orci. Praesent hendrerit nisl in mi venenatis, non sagittis enim tempor. Sed porta auctor posuere. Vestibulum feugiat pharetra sapien, quis fringilla arcu tempor eu. Nullam bibendum lorem nec egestas egestas. Nulla facilisi. Donec condimentum vehicula tortor, sit amet venenatis diam lobortis et. In maximus arcu sem, vel consectetur felis ultricies tincidunt.

Suspendisse magna dui, rutrum nec libero nec, cursus feugiat augue. Sed laoreet dolor justo, lobortis condimentum enim porttitor vel. Vestibulum eget euismod neque. Donec tempus massa et orci scelerisque, nec consectetur elit maximus. Nullam congue tellus eget risus maximus elementum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet ultrices velit. Suspendisse viverra sem lorem, et fermentum quam hendrerit ac. Phasellus quis ullamcorper ex. Pellentesque tempor velit erat, et pellentesque lorem venenatis eu. Donec id diam gravida libero vulputate finibus sed ut est. Mauris viverra ornare nisl, a semper ante venenatis eget. Fusce metus metus, viverra nec luctus id, porta nec lectus.

Nulla dignissim non purus quis viverra. Cras viverra, quam eu dapibus lobortis, sem arcu fermentum libero, at elementum nunc orci sit amet lorem. Ut tristique nulla non nibh maximus ullamcorper. Aenean vitae urna nec turpis viverra rhoncus. Maecenas sed dolor nec tellus aliquet egestas nec vitae nibh. Curabitur varius venenatis risus, et consequat elit accumsan nec. Integer commodo vehicula euismod. Nullam vitae mi quis est rhoncus imperdiet vitae efficitur orci. Integer iaculis orci eu dui volutpat, quis sollicitudin est dapibus. Aenean gravida malesuada purus sed sollicitudin. Donec et aliquam metus. Pellentesque ac semper tortor. Sed lacinia dolor sit amet accumsan mattis.

Duis non sapien a ex malesuada pharetra bibendum non velit. Quisque sed turpis eu mi imperdiet cursus ut vel purus. Ut volutpat, orci volutpat viverra tincidunt, nulla massa vulputate leo, non semper urna velit eu turpis. Duis ultrices urna tortor, quis congue massa mattis sit amet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin mauris est, convallis eget sagittis ut, gravida vitae libero. Donec non nulla a risus congue mollis eget nec orci. Donec lobortis ante id ex mollis, eu pellentesque libero congue. Etiam luctus turpis id ipsum pharetra, ut pulvinar risus consectetur. Sed nec libero erat. Nullam nisi nunc, ullamcorper a mauris ut, volutpat sodales massa. Etiam tincidunt urna laoreet nisi sagittis hendrerit. Pellentesque porttitor metus eget iaculis aliquam.

Proin a velit fringilla, facilisis nisl id, sollicitudin justo. Aliquam dignissim felis non turpis vestibulum, vel laoreet metus bibendum. Fusce id nisi purus. Nullam at lectus sed orci placerat elementum nec sed ex. Aenean interdum vel massa nec finibus. Morbi nec libero ante. In nulla mauris, scelerisque in dictum id, scelerisque id urna. Donec enim eros, convallis at metus non, feugiat tempus magna. Integer tempor, magna ut cursus consequat, augue justo pretium metus, ut blandit leo magna eu tortor. Nunc vitae aliquam massa, ut molestie sem. Sed non tortor imperdiet, laoreet leo a, bibendum neque. Integer non fermentum nibh, quis dictum ex. Mauris semper porta interdum.
            </div>
        );
    }
}

export default Politica;